Database:
  DBType: mysql
  UserName: root
  Password: password
  Host: 127.0.0.1:3306
  DBName: dig
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Server:
  # available run mode: debug release test
  RunMode: debug
  HttpPort: 8880
  ReadTimeout: 60
  WriteTimeout: 60
Redis:
  Addr: 127.0.0.1:6379
  Password:
  DB: 0
PostgreSQL:
  DBUrl: postgres://postgres:123456@localhost:5432/postgres?sslmode=disable
PostgreORM:
  DSN: host=localhost user=postgres password=123456 dbname=postgres port=5432 sslmode=disable TimeZone=Asia/Shanghai
MiniProgramTest:
  AppID: wx1377d9fd449f5888
  AppSecret: e9f1ab92c0b6e1b838b4c46693c49d55
MiniProgram:
  AppID: wx019211331f8180f0
  AppSecret: ac7c76a285ab7e1ca48c3cbd28e80ce2